services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Change the left side to any path on your host machine
      # Examples:
      # - /home/username/audiobooks:/app/downloads
      # - /mnt/storage/audio:/app/downloads
      # - /Volumes/NAS/audiobooks:/app/downloads
      - ./downloads:/app/downloads
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --log-level info --reload