services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    volumes:
      # Downloads directory mapping (configure in .env file)
      - "${DOWNLOADS_HOST_PATH}:${DOWNLOADS_CONTAINER_PATH}"
    env_file:
      - .env
    command: >
      uvicorn app:app
        --host ${HOST}
        --port ${PORT}
        --log-level ${LOG_LEVEL}
        ${AUTO_RELOAD:+--reload}