services:
  web:
    build: .
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    volumes:
      # Downloads directory mapping (configure in .env file)
      - ${DOWNLOADS_HOST_PATH:-./downloads}:${DOWNLOADS_CONTAINER_PATH:-/app/downloads}
    environment:
      - PYTHONUNBUFFERED=${PYTHONUNBUFFERED:-1}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-1440}
      - PORT=${PORT:-8000}
      - HOST=${HOST:-0.0.0.0}
    env_file:
      - .env
    command: >
      uvicorn app:app 
      --host ${HOST:-0.0.0.0} 
      --port ${PORT:-8000} 
      --log-level ${LOG_LEVEL:-info}
      ${AUTO_RELOAD:+--reload}